name: ML Model Training Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This grants write permission to the workflow
    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Install Conda
        run: |
          # Install Conda
          wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh -O anaconda.sh
          bash anaconda.sh -b
          echo "export PATH=$HOME/anaconda3/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc
          conda init bash

      - name: Set up Conda environment
        run: |
          conda create -n mlflow python=3.12.2 -y
          conda init
          conda activate mlflow
          conda install -c conda-forge mlflow scikit-learn pandas numpy matplotlib seaborn joblib

      - name: Check Conda Environment
        run: |
          conda info --envs  # Ensure the environment exists
          conda init
          conda activate mlflow
          python --version
          pip --version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy matplotlib seaborn joblib
          if [ -f MLProject/requirements.txt ]; then pip install -r MLProject/requirements.txt; fi

      - name: Upload dataset to the job
        run: |
          echo "Copying dataset for training..."
          cp MLProject/preprocessing/preprocessed_dataset.csv ./MLProject/

      - name: Run mlflow project
        run: |
          conda init
          conda activate mlflow
          mlflow run MLProject -P dataset_path=./MLProject/preprocessing/preprocessed_dataset.csv
          
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          cd MLProject
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(order_by=['start_time DESC']).iloc[0]['run_id'])")
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          cd ..
          
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: MLProject/output/
          
      - name: Build Docker Model
        run: |
          cd MLProject
          # Build Docker image directly using MLflow
          mlflow models build-docker \
            -m "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
            -n "personality:${GITHUB_SHA}"  # Updated to 'personality'
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Tag Docker Image
        run: |
          docker tag personality:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/personality:latest  # Updated to 'personality'
          docker tag personality:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/personality:${GITHUB_SHA}  # Updated to 'personality'
          
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/personality:latest  # Updated to 'personality'
          docker push ${{ secrets.DOCKER_USERNAME }}/personality:${GITHUB_SHA}  # Updated to 'personality'
          
      - name: Post Log in to Docker Hub
        run: echo "Docker image pushed successfully to Docker Hub"
          
      - name: Complete job
        run: echo "Workflow completed successfully!"
