name: Advanced ML CI with MLflow + Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        pip install mlflow cloudpickle numpy pandas psutil scikit-learn scipy python-dotenv

    - name: Run training
      run: |
        python MLProject/modeling.py

    - name: Upload trained model artifact
      uses: actions/upload-artifact@v2
      with:
        name: trained_model
        path: MLProject/best_model_default.pkl

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m ./MLProject/model_default -n personality-image
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker tag personality-image $DOCKERHUB_USERNAME/personality-image:latest
        docker push $DOCKERHUB_USERNAME/personality-image:latest
